INSERT INTO sous_rubrique (nom_sous_rubrique, photo_sous_rubrique, id_rubrique) VALUES
('Guitares', 'guitares.jpg', 1),
('Basses', 'basses.jpg', 1),
('Pianos', 'pianos.jpg', 2),
('Synthétiseurs', 'synthes.jpg', 2),
('Batteries', 'batteries.jpg', 3),
('Congas', 'congas.jpg', 3),
('Trompettes', 'trompettes.jpg', 4),
('Saxophones', 'saxophones.jpg', 4),
('Câbles', 'cables.jpg', 5),
('Supports', 'supports.jpg', 5),
('Clarinette', 'clarinette.jpg', 6),
('Flûte traversière', 'flute.jpg', 6),
('Enceintes', 'enceintes.jpg', 7),
('Tables de mixage', 'tables_mixage.jpg', 7),
('Projecteurs', 'projecteurs.jpg', 8),
('Pieds & Supports', 'pieds.jpg', 8),
('Interfaces audio', 'interfaces.jpg', 9),
('Claviers maîtres', 'claviers_maitres.jpg', 9),
('Partitions classiques', 'partitions_classiques.jpg', 10),
('Méthodes débutants', 'methodes_debutants.jpg', 10),
('Contrôleurs DJ', 'controleurs.jpg', 11),
('Logiciels DJ', 'logiciels_dj.jpg', 11),
('Microphones filaires', 'micros_filaires.jpg', 12),
('Microphones sans fil', 'micros_sans_fil.jpg', 12),
('Enregistreurs numériques', 'enregistreurs.jpg', 13),
('Studios portables', 'studios_portables.jpg', 13),
('Produits d’entretien', 'entretien.jpg', 14),
('Outils de réparation', 'outils.jpg', 14),
('Plugins VST', 'plugins.jpg', 15),
('Banques de sons', 'banques_sons.jpg', 15);
